import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import Footer from "./footer/page";



const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900' ], // Add the weights you need here
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        {/* Google Tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=AW-10888307324"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'AW-10888307324');
            `,
          }}
        />

        {/* Purchase Conversion Event Snippet */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              function gtag_report_conversion(url) {
                var callback = function () {
                  if (typeof(url) != 'undefined') {
                    window.location = url;
                  }
                };
                gtag('event', 'conversion', {
                  'send_to': 'AW-10888307324/ul49CNav648YEPzE-cco',
                  'transaction_id': '',
                  'event_callback': callback
                });
                return false;
              }
            `,
          }}
        />

        {/* Google Shopping App Purchase Conversion Event Snippet */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              function gtag_report_conversion(url) {
                var callback = function () {
                  if (typeof(url) != 'undefined') {
                    window.location = url;
                  }
                };
                gtag('event', 'conversion', {
                  'send_to': 'AW-10888307324/vEMyCITyw5EYEPzE-cco',
                  'value': 0.0,
                  'currency': 'INR',
                  'transaction_id': '',
                  'event_callback': callback
                });
                return false;
              }
            `,
          }}
        />

        {/* Leads Conversion Event Snippet */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              gtag('event', 'conversion', {'send_to': 'AW-10888307324/rtPdCIum6csYEPzE-cco'});
            `,
          }}
        />
        </head>
      <body className={poppins.className}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
